sudo: required
services:
  - docker

before_install:
  - docker build -t inudog/docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true inudog/docker-kubernetes npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "uDockerFrontend"
  env: "UDockerFrontend-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-772742945665"
  bucket_path: "uDockerFrontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_KEY